### PR TITLE
R Cloud Object Storage Support

### PR DESCRIPTION
**Pull request by bassel-zeidan**

### CODE REVIEW

**Comment by bassel-zeidan** [comment]
Testing:
https://apsportal.ibm.com/analytics/notebooks/f276df70-0ea4-421e-9aee-5af2bc1acac4/view?access_token=808d15a872640f77121ab14dc5268c4d8b1ad8a0c86158f3888d3b54cbe91d8f

**Comment by bassel-zeidan** [comment]
Hello @jimcrozier,
could you please take a look at this PR? If we want to release a new version for R are there any guides or documentations for doing so?

**Comment by bassel-zeidan** [comment]
fyi @gadamc

**Comment by gadamc** [comment]
Looks good for me. Merge when ready.

**Pull request merged**
